quarkus.application.version=1.0.1
quarkus.application.ui-header=SaveQL
quarkus.test.continuous-testing=disabled
quarkus.live-reload.instrumentation=true
%dev.quarkus.http.host=0.0.0.0
quarkus.banner.enabled=false

quarkus.log.console.format=[%d{HH:mm:ss}] %-5p > %s%e%n
quarkus.log.level=INFO

saveql.crypto.secret=!_-+#__-+#__-+#__-+#20_WELCOME_TO_SAVEQL26_-+#__-+#__-+#__-+#_!

saveql.mail.templates.repository=saveql/mail-templates
saveql.mail.templates.branch=master

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/saveql
quarkus.datasource.username=saveql
quarkus.datasource.password=mysecretpassword

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.datasource.devservices.enabled=false
