quarkus.application.version=1.0.1
quarkus.application.ui-header=SaveQL
quarkus.test.continuous-testing=disabled
quarkus.live-reload.instrumentation=true
quarkus.http.host=0.0.0.0
# remove quarkus.http.host when in production
quarkus.banner.enabled=false

quarkus.log.console.format=[%d{HH:mm:ss}] %-5p> %s%e%n
quarkus.log.level=INFO